### ISSUE TITLE
sh build.sh --cpu arm64 results in linker command failure.

### ISSUE THREAD

**Issue by QuixoticValentine** [nim-lang/csources_v1#1]
With the resulting error code

OS: macosx
 CPU: arm
clang -o ../bin/nim -ldl -lm
Undefined symbols for architecture arm64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Araq** [comment]
What does ``sh build.sh`` produce? It should detect the CPU now automatically.

**Comment by QuixoticValentine** [comment]
> What does `sh build.sh` produce? It should detect the CPU now automatically.

It still produces the same error.

**Comment by Araq** [comment]
Ok, thanks. Bummer.

**Comment by Araq** [comment]
It works on my M1, closing. Please reopen if still a problem for you.
